path_of_input_file=r'D:\Programing\scrapy\aaa.xlsx'
path_of_output_file=r'D:\Programing\scrapy\out.xlsx'
path_of_chrome_driver=r'D:\Programing\scrapy\chrome\chromedriver.exe'
linkedin_email='brian.coney2017@yandex.com'
linkedin_password='abcABC123!@#'
